### ISSUE TITLE
eden services -i pg - failed due to nested credentials

### ISSUE THREAD

**Issue by drnic** [starkandwayne/eden#1]
```
$ eden services -i pg2
pg2	postgresql93	free
Could not marshal credentials: json: unsupported type: map[interface {}]interface {}
```

`~/.eden/config` shows the binding containers nested `ports` key:

```
- id: d21418ad-edf1-402b-a181-1418bb4779ad
  name: pg2
  service_id: 2fd814ac-d1f7-4d4a-a4f7-d386cd8fd8e3
  service_name: postgresql93
  plan_id: 1a0efffc-eb45-4bf8-8ee3-a3c1a9a53151
  plan_name: free
  broker_url: http://54.159.121.202:5000
  bindings:
  - id: 74ed9dfb-53b0-4758-8fe4-a698123e1916
    name: postgresql93-74ed9dfb-53b0-4758-8fe4-a698123e1916
    credentials:
      dbname: zohlh6ebvhuajwve
      hostname: host-01.docker.com
      password: gqumzsyua6qo7mtd
      port: "32769"
      ports:
        5432/tcp: "32769"
      uri: postgres://ao5cu6bfcsew62l5:gqumzsyua6qo7mtd@host-01.docker.com:32769/zohlh6ebvhuajwve
      username: ao5cu6bfcsew62l5
    created_at: 2017-04-09T17:55:35.620934013+10:00
  created_at: 2017-04-09T17:55:16.833969356+10:00
```

If `ports: {5432/tcp: "32769"}` is removed from the file, the command works.
